### ISSUE TITLE
License wrongly abbreviated as LGPL (should be GPL)

### ISSUE THREAD

**Issue by jonassmedegaard** [konclude/Konclude#1]
License is declared in many places to be `under the terms of version 3 of the GNU General Public License (LGPLv3)` - i.e. GPL but with LGPL in parenthesis.

**Comment by andreas-steigmiller** [comment]
Many thanks for pointing out the license issues. Now all file heades should correctly refer to version 3 of the GNU Lesser General Public License (LGPLv3).

**Comment by jonassmedegaard** [comment]
When all is licensed LGPL-3, you might wanna drop needless file `GPL.txt`.

**Comment by andreas-steigmiller** [comment]
As far as I know, both files are required (i.e., `LGPL-3.0.txt` and `GPL.txt`) since the `LGPL-3.0.txt` file refers to the terms and conditions of the GPLv3 (in contrast to the LGPL2 license file):

> This version of the GNU Lesser General Public License incorporates the terms and conditions of version 3 of the GNU General Public License, supplemented by the additional permissions listed below.

**Comment by jonassmedegaard** [comment]
Quoting andreas-steigmiller (2019-10-08 20:29:18)
> As far as I know, both files are required (i.e., `LGPL-3.0.txt` and `GPL.txt`) since the `LGPL-3.0.txt` file refers to the terms and conditions of the GPLv3 (in contrast to the LGPL2 license file):
> 
> > This version of the GNU Lesser General Public License incorporates the terms and conditions of version 3 of the GNU General Public License, supplemented by the additional permissions listed below.

Ah. I learned something new today :-)

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
