### ISSUE TITLE
warning with complex rasqal query: assertion failed: object pointer of type librdf_statement is NULL

### ISSUE THREAD

**Issue by jonassmedegaard** [konclude/Konclude#13]
When I test `Tests/lubm-univ-bench-sparql-load-and-complex-query-rasqal-test.sparql` I get warnings on stderr:
```
rdf_model.c:1527: (librdf_model_find_statements_in_context) assertion failed: object pointer of type librdf_statement is NULL.
rdf_model.c:1527: (librdf_model_find_statements_in_context) assertion failed: object pointer of type librdf_statement is NULL.
```

**Comment by andreas-steigmiller** [comment]
Many thanks for reporting the error. I set the librdf_statement to NULL since it was not required for Konclude, which worked quite well on Windows, but apparently not on Linux. I will try to push a small update within the next hours that should resolve the issue.

**Comment by jonassmedegaard** [comment]
That was quick. Thanks!

I can confirm that it works now.
