### ISSUE TITLE
classify using data property values?

### ISSUE THREAD

**Issue by wdduncan** [konclude/Konclude#18]
Does Konclude classify using data property values. For example, if I define an adult as:
```
person and (has_age some xsd:integer[> 18])
```
will Konclude class individuals with ages greater than 18 as being adults?

**Comment by andreas-steigmiller** [comment]
Yes, Konclude should consider data property values for classification and realization. But please note that there are some limitations on some data property values (e.g., number support is limited to 64-bit, no regular expressions for strings).
