### ISSUE TITLE
SPARQL example files missing, and command in Readme.md broken

### ISSUE THREAD

**Issue by jonassmedegaard** [konclude/Konclude#4]
Hi,

I am excited to explore the newly introduced SPARQL interface.

`Readme.md` contains this:
> ./Konclude spraqlfile -i Tests/sparql-load-and-query-test.sparql -o Tests/query-answers.xml -c Configs/querying-config.xml

Unfortunately it seems that the example file `Tests/sparql-load-and-query-test.sparql` is missing.

Also, the (sub)command is `sparqlfile` (not `spraglfile` which seems a mere typo).

**Comment by andreas-steigmiller** [comment]
Many thanks for the pointing out the issues. I will try to fix them tomorrow. We are currently running a lot of tests and evaluations and as soon as everything is/seems stable, we will make a real new release.

**Comment by andreas-steigmiller** [comment]
Again many thanks for the report. I added some examples and updated the readme.

**Comment by jonassmedegaard** [comment]
Thanks for improving documentation.

I realize that I bundled two issues into a single report and you seemingly acted on only one of them here. I have therefore separately filed #9 for the still open issue.
