### ISSUE TITLE
(sub)commands randomly does nothing

### ISSUE THREAD

**Issue by jonassmedegaard** [konclude/Konclude#8]
It seems that any (sub)command randomly - 10%-40% of the times - fails by simply doing nothing.

Running `watch Konclude -h` and simply watching the output, randomly it emits only the initial 3 lines until and including the version number.

**Comment by jonassmedegaard** [comment]
This issue seems to occur only with the recent prereleases.

**Comment by andreas-steigmiller** [comment]
Many thanks for reporting it. It should know be fixed at least for showing the help information with `-h` (which was a more or less a known issue, where the main thread didn't wait until the log message was printed out). For other commands, I didn't observe anything like this on my plattforms.

**Comment by jonassmedegaard** [comment]
yes, I can confirm that it is now fixed (for some time).
