### ISSUE TITLE
SPARQL example files missing

### ISSUE THREAD

**Issue by jonassmedegaard** [konclude/Konclude#9]
The following files, mentioned (since git commit 7991161) in both `Readme.md`and help output, is missing from the project:

* Tests/sparql-load-and-query-test.sparql
* Tests/sparql-existential-variables-query-test.sparql

**Comment by andreas-steigmiller** [comment]
They should be there since git commit 2ebb5b4 (but they were indeed missing in commit 7991161). Sorry for the inconvenience.

**Comment by jonassmedegaard** [comment]
Quoting andreas-steigmiller (2019-10-09 20:36:13)
> They should be there since git commit 2ebb5b4 (but they were indeed missing in commit 7991161).

Excellent. Thanks!

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
